.PHONY: clean All

All:
	@echo "==========Building project:[ DefaultProjectCprogramming - Debug ]=========="
	@cd "DefaultProjectCprogramming" && "$(MAKE)" -f  "DefaultProjectCprogramming.mk"
clean:
	@echo "==========Cleaning project:[ DefaultProjectCprogramming - Debug ]----------"
	@cd "DefaultProjectCprogramming" && "$(MAKE)" -f  "DefaultProjectCprogramming.mk" clean
