.PHONY: clean All

All:
	@echo "==========Building project:[ OurFirstProgram - Debug ]=========="
	@cd "OurFirstProgram" && "$(MAKE)" -f  "OurFirstProgram.mk"
clean:
	@echo "==========Cleaning project:[ OurFirstProgram - Debug ]----------"
	@cd "OurFirstProgram" && "$(MAKE)" -f  "OurFirstProgram.mk" clean
