.PHONY: clean All

All:
	@echo "==========Building project:[ TestProject - Debug ]=========="
	@cd "TestProject" && "$(MAKE)" -f  "TestProject.mk"
clean:
	@echo "==========Cleaning project:[ TestProject - Debug ]----------"
	@cd "TestProject" && "$(MAKE)" -f  "TestProject.mk" clean
